# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: let
  acer-module = pkgs.custom.acer-module;
  acer-wmi-battery = pkgs.custom.acer-wmi-battery;
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.kernelPackages = pkgs.linuxPackages_latest;

  # NOTE: Look at the top comment
  boot.extraModulePackages = [acer-module acer-wmi-battery];
  boot.kernelModules = ["kvm-intel" "facer" "wmi" "sparse-keymap" "video" "acer-wmi-battery"];

  boot.kernelParams = ["nvidia_drm.fbdev=1"];
  boot.initrd.kernelModules = ["nvidia" "i915" "nvidia_modeset" "nvidia_uvm" "nvidia_drm"];
  boot.initrd.availableKernelModules = ["vmd" "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc"];

  # NOTE: For future me, just replace these when you reinstall nixos
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5a482d52-1fed-473e-93da-ccc23ca44398";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C21D-32B3";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/6fdcc1c7-99e2-4809-83ab-6495a2ad05f2";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.wlan0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp109s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Actual Hardware config
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.firmware = with pkgs; [
    sof-firmware # NOTE: This is just to explicitly declare sof-firmware because it doesn't work sometimes
  ];

  # NOTE: This is hardware config from the custom nixos modules, moved it here because it is more fitting
  hardware = {
    audio.enable = true;
    batteryOptimization.enable = true;
    bluetooth.enable = true;
    drawingTablet.enable = false; # Currently using an EOL version of dotnet
    networking.enable = true;
    nvidia = {
      enable = true;
      graphicsExtraPackages = with pkgs; [intel-media-driver];
      intelBusId = "PCI:1:0:0";
      nvidiaBusId = "PCI:0:2:0";
    };
  };
}
